---
- name: Create InfluxDB data directory
  file: path=/root/influxdb state=directory

- name: Pull InfluxDB image
  docker_image:
    name: influxdb

- name: Run InfluxDB 
  docker_container:
    name: influxdb-node
    image: influxdb
    state: started
    network_mode: host
    volumes:
      - /root/influxdb:/var/lib/influxdb
    env:
      INFLUXDB_GRAPHITE_ENABLED: "true"